#! /bin/sh

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config focused_border_color  "#8EC07C"
bspc config normal_border_color "#000"
bspc config window_gap           10
bspc config focus_follows_pointer false

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty desktop='^1'
# bspc rule -a qutebrowser desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a Postman desktop='^3'
bspc rule -a TelegramDesktop desktop='^4'

kitty &
# mpd &
# picom --config ~/.config/bspwm/picom.conf &
feh --bg-fill  ~/.config/wallpaper/forestpath.jpg
~/.config/bspwm/polybar/launch.sh
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &
